# Zerops configuration for Frappe/ERPNext deployment
# Creates managed database services and uses Docker Compose for application containers

# Managed Services have to be executed in Zerops GUI using 'Import services'
services:
    - hostname: mariadb
      # service type and version number in mariadb@{version} format
      type: mariadb@10.6
      # mode of operation "HA"/"NON_HA",
      mode: NON_HA

    - hostname: rediscache
      type: valkey@7.2
      mode: NON_HA  # use HA in production
    
    - hostname: redisqueue
      type: valkey@7.2
      mode: NON_HA  # use HA in production

    - hostname: sharedstorage
      type: shared-storage
      mode: NON_HA

zerops:
  # Frappe/ERPNext Application Services (Docker Compose)
  - setup: erpnext
    build:
      # Deploy the custom docker-compose file and scripts to the runtime
      deployFiles: 
        - ./docker-compose.zerops.yaml
        - ./scripts/
      addToRunPrepare: 
        - ./docker-compose.zerops.yaml
        - ./scripts/
    run:
      # Environment variables for Docker Compose services
      envVariables:
        # Image configuration
        CUSTOM_IMAGE: frappe/erpnext
        CUSTOM_TAG: v15.84.0
        ERPNEXT_VERSION: v15.84.0
        PULL_POLICY: always
        RESTART_POLICY: unless-stopped
        
        # Database connection (using Zerops service)
        DB_HOST: ${mariadb_hostname}
        DB_PORT: 3306
        ROOT_USER: ${mariadb_user}
        DB_PASSWORD: ${mariadb_password}

        # Redis connections (using Zerops Valkey services)
        REDIS_CACHE: rediscache:6379
        REDIS_QUEUE: redisqueue:6379

        # Site configuration
        FRAPPE_SITE_NAME_HEADER: ${siteName}
        ADMIN_PASSWORD: ${adminPassword}
        
        # Frontend/Nginx configuration
        UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
        UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
        UPSTREAM_REAL_IP_RECURSIVE: "off"
        PROXY_READ_TIMEOUT: 120
        CLIENT_MAX_BODY_SIZE: 50m
      
      # Site initialization and app installation
      prepareCommands:
        # Check service connections before proceeding
        # - chmod +x scripts/check-connections.sh
        # - ./scripts/check-connections.sh

        # Pull Docker images
        - docker compose -f docker-compose.zerops.yaml pull
        
        # Install Frappe site and apps using dedicated script
        - |
          echo "🚀 Running site installation..."
          chmod +x scripts/install-site.sh
          ./scripts/install-site.sh
          echo "✅ Site installation completed"
      
      # Start all application services
      start: docker compose -f docker-compose.zerops.yaml up --force-recreate
      
      # Expose the frontend port
      ports:
        - port: 8080
          httpSupport: true

# Required secrets in Zerops dashboard:
# - dbPassword: Database password for MariaDB (e.g., "mySecureDbPassword123")
# - adminPassword: ERPNext admin user password (e.g., "myAdminPassword123")
# - siteName: Your site domain name (e.g., "mycompany.example.com")
#
# This configuration provides:
# ✅ Managed MariaDB service with automatic backups and scaling
# ✅ Dedicated Redis services for cache and queue (better performance)
# ✅ Docker Compose for Frappe containers only (simpler, faster)
# ✅ Automatic site initialization with custom apps
# ✅ Persistent storage managed by Zerops
# ✅ Service health monitoring and auto-restart
# ✅ Built-in service discovery (services connect by name)
#
# Architecture:
# - db: Managed MariaDB 11 service (default Zerops configuration)
# - redis-cache: Managed Valkey 7.2 service (default configuration, NON_HA mode)  
# - redis-queue: Managed Valkey 7.2 service (default configuration, NON_HA mode)
# - app: Docker Compose with Frappe containers (backend, frontend, websocket, workers, scheduler)
#
# Benefits of managed services:
# - Automatic backups and point-in-time recovery
# - Built-in monitoring and alerting
# - Automatic security updates
# - High availability and failover
# - Performance optimization
# - No container overhead for databases